"""Pytest entry for the V1 vs V2 extraction prompt snapshot-diff harness.

Run:

    # from repo root
    pytest apps/api/tests/extraction/test_snapshot_diff.py -v

The test builds a fresh ``SnapshotReport`` on every run and asserts the
structural invariants the baseline depends on. The actual baseline
report is regenerated by running ``run_snapshot_diff.py`` (or by
calling :func:`tests.extraction.snapshot_diff.render_baseline_markdown`
from a Python REPL).

We deliberately do NOT check the report into git as part of this test
run — the report is generated once and committed at
``docs/verification/NFM-3531-v1-v2-baseline.md`` by the CLI. The
pytest suite guards the harness logic so a regression in either path
surfaces as a unit failure rather than as a silent baseline drift.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.extraction.snapshot_diff import (
    SnapshotReport,
    build_snapshot_report,
    fixture_property_categories,
    load_golden_fixtures,
    render_baseline_markdown,
)
from tests.extraction.v1_prompt_legacy import (
    build_extraction_system_prompt_v1,
    list_v1_category_values,
    list_v1_standard_names,
)


REPO_ROOT = Path(__file__).resolve().parents[4]
GOLDEN_DIR = REPO_ROOT / "apps" / "api" / "tests" / "fixtures" / "golden"
BASELINE_MD = REPO_ROOT / "docs" / "verification" / "NFM-3531-v1-v2-baseline.md"


# ---------------------------------------------------------------------------
# Sanity guards — fail loudly if the inputs the harness depends on change.
# ---------------------------------------------------------------------------


def test_golden_set_loads() -> None:
    fixtures = load_golden_fixtures(GOLDEN_DIR)
    assert len(fixtures) >= 13, (
        f"Expected >=13 golden fixtures, found {len(fixtures)}; "
        "the snapshot-diff baseline depends on the full set"
    )
    cats = fixture_property_categories(fixtures)
    assert cats, "Golden set declares no property_category values; nothing to diff"


def test_v1_prompt_builds_and_has_expected_sections() -> None:
    prompt = build_extraction_system_prompt_v1()
    assert "## Property Categories (property_category)" in prompt
    assert "## Standard Property Names (property)" in prompt
    # V1 has 9 core + 2 supporting categories.
    assert len(list_v1_category_values()) == 11
    # Standard names must be a non-empty deterministic list.
    names = list_v1_standard_names()
    assert names == sorted(set(names))
    assert len(names) > 0


# ---------------------------------------------------------------------------
# Core harness — full snapshot report + invariants the report depends on.
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def report() -> SnapshotReport:
    return build_snapshot_report()


def test_snapshot_report_runs_in_under_5_minutes(report: SnapshotReport) -> None:
    """Sanity: the harness itself must complete quickly.

    The actual <5min budget applies to the full fixture-driven run on
    CI; this unit-level test guards against accidental quadratic
    regressions in the harness itself (e.g. an O(N^2) string diff in
    a hot loop).
    """
    assert report is not None
    assert isinstance(report.v1_prompt, str) and len(report.v1_prompt) > 0
    assert isinstance(report.v2_prompt, str) and len(report.v2_prompt) > 0


def test_v2_prompt_includes_ontology_sections(report: SnapshotReport) -> None:
    """The V2 path must still expose the same two dynamic sections."""
    assert "## Property Categories (property_category)" in report.v2_prompt
    assert "## Standard Property Names (property)" in report.v2_prompt


def test_v2_prompt_includes_ontology_context_block(report: SnapshotReport) -> None:
    """V2 distinguishes itself from V1 by injecting the ontology context block."""
    assert "## 本体定义 (Ontology)" in report.v2_prompt


def test_v1_prompt_does_not_inject_ontology_context(report: SnapshotReport) -> None:
    """V1 predates the ontology context feature and must not inject it."""
    assert "## 本体定义 (Ontology)" not in report.v1_prompt


def test_baseline_markdown_renders(report: SnapshotReport) -> None:
    md = render_baseline_markdown(report)
    assert md.startswith("# NFM-3531 V1 vs V2 extraction-prompt baseline")
    assert "## Summary" in md
    assert "## Categories block" in md
    assert "## Standard property names block" in md
    assert "## Golden-set category coverage" in md
    assert "## Verdict for NFM-3531-C merge gate" in md


def test_report_has_structural_sections(report: SnapshotReport) -> None:
    assert report.categories_section.list_diff is not None
    assert report.standard_names_section.list_diff is not None


def test_golden_set_coverage_is_100pct_when_v2_matches_v1(report: SnapshotReport) -> None:
    """A clean PASS-WITH-NOTES baseline still requires every golden
    category to be covered by BOTH paths."""
    if report.fixtures_diverged_count == 0:
        assert report.fixtures_covered_by_v2 == report.fixtures_covered_total
        assert report.fixtures_covered_by_v1 == report.fixtures_covered_total


def test_baseline_report_file_exists_when_committed() -> None:
    """The committed baseline file is what NFM-3531-C will diff against.

    This test guards against the file being accidentally deleted from
    the repo. The CI-FAILED NFM-848 case showed how easy it is to lose
    a verification artifact during a rebase — keeping an explicit
    existence check makes the loss loud rather than silent.
    """
    assert BASELINE_MD.exists(), (
        f"{BASELINE_MD} missing; regenerate with "
        "`python apps/api/tests/extraction/run_snapshot_diff.py` "
        "and commit the result."
    )
