"""Unit tests for scripts/check_prod_image_tag.py (NFM-4265).

Covers the 2026-09-04 NFM-4264 incident class: a 40-hex SHA pinned in
docker/.env.prod is silently inherited by any host-side
``docker compose --env-file docker/.env.prod up -d --build`` and re-tags
prod to a stale SHA while building current-tree content.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT_DIR = Path(__file__).resolve().parent.parent
SCRIPT_PATH = SCRIPT_DIR / "check_prod_image_tag.py"
DEPLOY_SCRIPT = SCRIPT_DIR / "deploy_prod.sh"
ENV_EXAMPLE = SCRIPT_DIR.parent / "docker" / ".env.prod.example"

# Stand-ins: OLD = the stale Sep-2 SHA from the incident, NEW = deploying SHA.
OLD_SHA = "dce00e62636f8df189d84e90df6d8377dc1f782d"
NEW_SHA = "8e29e906d300ce741ca32c4ba5c7d7558635aeba"


def guard_env(**extra: str) -> dict[str, str]:
    """Child env with any inherited PROD_IMAGE_TAG stripped."""
    env = {k: v for k, v in os.environ.items() if k != "PROD_IMAGE_TAG"}
    env.update(extra)
    return env


def run_guard(
    env_file: Path,
    *,
    expected: str | None = None,
    git_ref: str | None = None,
    repo: Path | None = None,
    shell_tag: str | None = None,
) -> subprocess.CompletedProcess[str]:
    cmd = [sys.executable, str(SCRIPT_PATH), "--env-file", str(env_file)]
    if expected is not None:
        cmd += ["--expected", expected]
    if git_ref is not None:
        cmd += ["--git-ref", git_ref]
    if repo is not None:
        cmd += ["--repo", str(repo)]
    env = guard_env()
    if shell_tag is not None:
        env["PROD_IMAGE_TAG"] = shell_tag
    return subprocess.run(cmd, capture_output=True, text=True, env=env)


def write_env_file(path: Path, tag_line: str | None) -> Path:
    lines = ["# generated by test", "PROD_API_HOST_PORT=8001"]
    if tag_line is not None:
        lines.append(tag_line)
    path.write_text("\n".join(lines) + "\n")
    return path


def make_git_repo(tmp_path: Path) -> tuple[Path, str]:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@example.com"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "t"], check=True)
    (repo / "f.txt").write_text("x\n")
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "-m", "init"], check=True)
    head = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return repo, head


# --------------------------------------------------------------------------
# Check 1 — the env-file landmine (NFM-4264): a SHA in docker/.env.prod is
# always wrong, even a fresh one, even when the shell overrides it.
# --------------------------------------------------------------------------


def test_envfile_pinned_stale_sha_fails(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", f"PROD_IMAGE_TAG={OLD_SHA}")
    proc = run_guard(env_file, expected=NEW_SHA)
    assert proc.returncode == 3
    combined = proc.stdout + proc.stderr
    assert "NFM-4264" in combined
    assert "latest" in combined
    assert "env-file" in combined or ".env.prod" in combined


def test_envfile_pinned_current_sha_still_fails(tmp_path):
    """A fresh SHA in the env-file goes stale on the next deploy — fail it too."""
    env_file = write_env_file(tmp_path / ".env.prod", f"PROD_IMAGE_TAG={NEW_SHA}")
    proc = run_guard(env_file, expected=NEW_SHA)
    assert proc.returncode == 3


def test_envfile_pinned_sha_fails_even_with_shell_override(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", f"PROD_IMAGE_TAG={OLD_SHA}")
    proc = run_guard(env_file, expected=NEW_SHA, shell_tag=NEW_SHA)
    assert proc.returncode == 3


def test_envfile_quoted_sha_detected(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", f'PROD_IMAGE_TAG="{OLD_SHA}"')
    proc = run_guard(env_file, expected=NEW_SHA)
    assert proc.returncode == 3


# --------------------------------------------------------------------------
# Check 2 — the effective tag (shell env > env-file > latest) must be either
# a non-SHA tag or the expected/target SHA.
# --------------------------------------------------------------------------


def test_envfile_latest_with_expected_passes(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")
    proc = run_guard(env_file, expected=NEW_SHA)
    assert proc.returncode == 0
    assert "latest" in proc.stdout


def test_envfile_without_tag_passes(tmp_path):
    """Removing the line entirely is equally valid — compose falls back to latest."""
    env_file = write_env_file(tmp_path / ".env.prod", None)
    proc = run_guard(env_file, expected=NEW_SHA)
    assert proc.returncode == 0


def test_shell_sha_matching_expected_passes(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")
    proc = run_guard(env_file, expected=NEW_SHA, shell_tag=NEW_SHA)
    assert proc.returncode == 0


def test_shell_stale_sha_mismatch_fails(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")
    proc = run_guard(env_file, expected=NEW_SHA, shell_tag=OLD_SHA)
    assert proc.returncode == 2
    combined = proc.stdout + proc.stderr
    assert OLD_SHA[:8] in combined
    assert NEW_SHA[:8] in combined


def test_nonsha_tag_passes(tmp_path):
    """Version tags are not audit-destroying — only 40-hex SHAs are checked."""
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")
    proc = run_guard(env_file, expected=NEW_SHA, shell_tag="v1.2.3")
    assert proc.returncode == 0


def test_no_expected_resolves_git_ref(tmp_path):
    repo, head = make_git_repo(tmp_path)
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")

    matching = run_guard(env_file, git_ref="HEAD", repo=repo, shell_tag=head)
    assert matching.returncode == 0

    stale = run_guard(env_file, git_ref="HEAD", repo=repo, shell_tag=OLD_SHA)
    assert stale.returncode == 2


# --------------------------------------------------------------------------
# Config errors
# --------------------------------------------------------------------------


def test_missing_env_file_is_config_error(tmp_path):
    proc = run_guard(tmp_path / "does-not-exist.env", expected=NEW_SHA)
    assert proc.returncode == 4
    assert "not found" in (proc.stdout + proc.stderr)


def test_no_expected_and_unresolvable_ref_is_config_error(tmp_path):
    env_file = write_env_file(tmp_path / ".env.prod", "PROD_IMAGE_TAG=latest")
    repo, _head = make_git_repo(tmp_path)
    proc = run_guard(env_file, git_ref="no-such-ref", repo=repo)
    assert proc.returncode == 4


# --------------------------------------------------------------------------
# Wiring guard — executing deploy_prod.sh end to end on a fake host, and the
# tracked example must not model a SHA pin.
# --------------------------------------------------------------------------

# deploy_prod.sh prepends these to PATH before the inherited one, so a real
# docker there wins over any stub; the stub only serves hosts without one.
DEPLOY_PATH_PREFIXES = ("/usr/local/bin", "/usr/local/sbin", "/opt/homebrew/bin")


def write_executable(path: Path, body: str) -> Path:
    path.write_text(body)
    path.chmod(0o755)
    return path


def make_deploy_sandbox(
    tmp_path: Path, env_prod_line: str | None
) -> tuple[Path, Path, Path]:
    """Fake deploy host: HOME (so ``cd ~/Projects/nucpot`` lands in the
    sandbox) holding a real git repo with a local bare origin, plus a stub
    docker on PATH that records every invocation."""
    home = tmp_path / "home"
    repo = home / "Projects" / "nucpot"
    (repo / "scripts").mkdir(parents=True)
    (repo / "docker").mkdir(parents=True)
    shutil.copy2(DEPLOY_SCRIPT, repo / "scripts" / "deploy_prod.sh")
    shutil.copy2(SCRIPT_PATH, repo / "scripts" / "check_prod_image_tag.py")
    write_env_file(repo / "docker" / ".env.prod", env_prod_line)

    bare = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", str(bare)], check=True)
    subprocess.run(
        ["git", "-C", str(bare), "symbolic-ref", "HEAD", "refs/heads/main"], check=True
    )
    subprocess.run(["git", "-C", str(repo), "init", "-q"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@example.com"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "t"], check=True)
    subprocess.run(["git", "-C", str(repo), "remote", "add", "origin", str(bare)], check=True)
    subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "-m", "init"], check=True)
    subprocess.run(["git", "-C", str(repo), "branch", "-M", "main"], check=True)
    subprocess.run(["git", "-C", str(repo), "push", "-q", "origin", "main"], check=True)

    bin_dir = tmp_path / "stub-bin"
    bin_dir.mkdir()
    docker_log = tmp_path / "docker-calls.log"
    stub_body = (
        '#!/usr/bin/env bash\n'
        'printf "%s\\n" "docker $*" >> "$DOCKER_STUB_LOG"\n'
        "exit 0\n"
    )
    write_executable(bin_dir / "docker", stub_body)
    # A real docker (Docker Desktop) resolves compose via the DOCKER_CONFIG
    # override dir the script populates — it symlinks ~/.docker/cli-plugins/
    # docker-compose there, so provide one that answers the CLI's
    # docker-cli-plugin-metadata handshake.
    plugin_body = (
        '#!/usr/bin/env bash\n'
        'if [ "$1" = "docker-cli-plugin-metadata" ]; then\n'
        '  printf \'{"SchemaVersion":"0.1.0","Vendor":"test",'
        '"Version":"1.0","ShortDescription":"stub compose"}\\n\'\n'
        "  exit 0\n"
        "fi\n"
        'printf "%s\\n" "docker-compose $*" >> "$DOCKER_STUB_LOG"\n'
        "exit 0\n"
    )
    cli_plugins = home / ".docker" / "cli-plugins"
    cli_plugins.mkdir(parents=True)
    write_executable(cli_plugins / "docker-compose", plugin_body)
    return home, bin_dir, docker_log


def skip_if_host_docker_lacks_compose(bin_dir: Path) -> None:
    """The stub can only shadow docker on hosts with none in the PATH
    prefixes deploy_prod.sh hardcodes; probe a real one if it wins."""
    search_path = [Path(p) for p in DEPLOY_PATH_PREFIXES] + [
        bin_dir,
        Path("/usr/bin"),
        Path("/bin"),
    ]
    for directory in search_path:
        docker = directory / "docker"
        if not docker.is_file():
            continue
        if docker.parent == bin_dir:
            return
        probe = subprocess.run(
            [str(docker), "compose", "version"], capture_output=True
        )
        if probe.returncode != 0:
            pytest.skip(f"docker at {docker} cannot run 'compose version'")
        return


def run_deploy_prod(
    home: Path, bin_dir: Path, docker_log: Path, deploy_sha: str
) -> subprocess.CompletedProcess[str]:
    env = {k: v for k, v in os.environ.items() if k != "PROD_IMAGE_TAG"}
    env.update(
        {
            "HOME": str(home),
            "PATH": f"{bin_dir}{os.pathsep}/usr/bin:/bin",
            "DEPLOY_SHA": deploy_sha,
            "DOCKER_STUB_LOG": str(docker_log),
        }
    )
    script = home / "Projects" / "nucpot" / "scripts" / "deploy_prod.sh"
    return subprocess.run(
        ["/bin/bash", str(script)],
        capture_output=True,
        text=True,
        env=env,
        timeout=100,
    )


def test_deploy_prod_sh_aborts_before_build_when_env_prod_pins_sha(tmp_path):
    home, bin_dir, docker_log = make_deploy_sandbox(
        tmp_path, f"PROD_IMAGE_TAG={OLD_SHA}"
    )
    skip_if_host_docker_lacks_compose(bin_dir)
    proc = run_deploy_prod(home, bin_dir, docker_log, NEW_SHA)
    assert proc.returncode == 1
    combined = proc.stdout + proc.stderr
    assert "NFM-4265" in combined
    assert "Building nucpot-prod-api" not in proc.stdout
    if docker_log.exists():
        assert "build" not in docker_log.read_text()


def test_env_example_never_pins_sha():
    for raw in ENV_EXAMPLE.read_text().splitlines():
        line = raw.strip()
        if line.startswith("PROD_IMAGE_TAG="):
            value = line.partition("=")[2].strip().strip('"').strip("'")
            assert len(value) != 40 or not all(c in "0123456789abcdef" for c in value.lower()), (
                "docker/.env.prod.example must not model a SHA pin (NFM-4265)"
            )
