"""seed property_types for OntoFuel ingest

Revision ID: 031_seed_property_types
Revises: 030_create_corpus_table
Create Date: 2026-07-29

NFM-1995 (NFM-1985-BUG2): Seed the canonical ``property_types`` rows so the
OntoFuel ingest lookup at
``extraction_to_db_mapper._lookup_property_type`` can resolve every
property name emitted by the v4 extraction pipeline.  Without this seed
the dev/prod DB starts with ``property_types`` empty and every ingest
silently records ``created_measurements=0``.

* **Idempotent** — uses ``INSERT ... ON CONFLICT (category_id, slug) DO
  NOTHING`` keyed on the existing unique constraint
  ``uq_property_types_category_slug``.  Running the migration twice does
  not raise or duplicate rows.
* **Schema-only prerequisite** — requires the ``property_categories``
  rows created by ``010_seed_phase1_reference_data``.  Migration 010 is
  already in the linear chain, so by the time 031 runs the lookup by
  slug is guaranteed to succeed.
* **Coordinated with the mapper** — category slugs here match
  ``ONTOFUEL_CATEGORY_TO_SLUG`` in
  ``src/nfm_db/services/extraction_to_db_mapper.py``.  Diffuse OntoFuel
  literals (``diffusion``, ``irradiation``, ``other``) are translated to
  the broader DB slugs by the mapper; this seed targets the canonical
  slugs that the mapper ultimately writes against.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "031_seed_property_types"
down_revision: str | Sequence[str] | None = "030_create_corpus_table"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Seed payload
# ---------------------------------------------------------------------------
# Format: (category_slug, name, slug, value_type, description)
#
# value_type must be one of ('scalar', 'range', 'expression', 'list',
# 'text') per the check constraint
# ``ck_property_types_value_type`` declared in
# ``src/nfm_db/models/property.py``.

_PROPERTY_TYPE_SEED: tuple[tuple[str, str, str, str, str | None], ...] = (
    # ---- physical ----
    ("physical", "density",                "density",                "scalar", "Mass density (g/cm3 or kg/m3)"),
    ("physical", "lattice_constant",       "lattice_constant",       "scalar", "Equilibrium lattice parameter (Angstrom)"),
    ("physical", "cohesive_energy",        "cohesive_energy",        "scalar", "Cohesive energy per atom (eV)"),
    ("physical", "formation_energy",       "formation_energy",       "scalar", "Formation energy (eV/atom)"),
    ("physical", "melting_point",          "melting_point",          "scalar", "Melting temperature (K)"),
    # ---- mechanical ----
    ("mechanical", "bulk_modulus",         "bulk_modulus",           "scalar", "Bulk modulus (GPa)"),
    ("mechanical", "youngs_modulus",       "youngs_modulus",         "scalar", "Young's modulus (GPa)"),
    ("mechanical", "yield_strength",       "yield_strength",         "scalar", "Yield strength (MPa)"),
    ("mechanical", "elastic_constants",    "elastic_constants",      "list",   "Elastic constant tensor (C_ij in GPa)"),
    # ---- thermal ----
    ("thermal", "thermal_conductivity",    "thermal_conductivity",   "scalar", "Thermal conductivity (W/m.K)"),
    ("thermal", "thermal_expansion",       "thermal_expansion",      "scalar", "Linear thermal expansion coefficient (1/K)"),
    ("thermal", "specific_heat",          "specific_heat",          "scalar", "Specific heat capacity (J/kg.K)"),
    # ---- nuclear ----
    ("nuclear", "fission_cross_section",   "fission_cross_section",  "scalar", "Fission cross-section (barn)"),
    ("nuclear", "swelling_rate",           "swelling_rate",          "scalar", "Irradiation-induced swelling rate (%/dpa)"),
    # ---- diffusion (OntoFuel literal; maps to physical per ONTOFUEL_CATEGORY_TO_SLUG) ----
    ("physical", "diffusion_coefficient",  "diffusion_coefficient",  "scalar", "Diffusion coefficient (m2/s)"),
)


def upgrade() -> None:
    """Insert canonical property_types rows idempotently.

    Resolves ``category_id`` via a subquery against
    ``property_categories.slug`` so the seed is portable across
    environments (UUIDs are randomly generated by the model default).
    """
    for category_slug, name, slug, value_type, description in _PROPERTY_TYPE_SEED:
        op.execute(
            """
            INSERT INTO property_types
                (category_id, name, slug, value_type, description, created_at, updated_at)
            SELECT
                pc.id,
                ins.name,
                ins.slug,
                ins.value_type,
                ins.description,
                NOW(),
                NOW()
            FROM (SELECT CAST(:name AS VARCHAR) AS name,
                         CAST(:slug AS VARCHAR) AS slug,
                         CAST(:value_type AS VARCHAR) AS value_type,
                         CAST(:description AS TEXT) AS description) AS ins
            CROSS JOIN (
                SELECT id FROM property_categories WHERE slug = :category_slug
            ) AS pc
            ON CONFLICT (category_id, slug) DO NOTHING
            """,
            {
                "name": name,
                "slug": slug,
                "value_type": value_type,
                "description": description,
                "category_slug": category_slug,
            },
        )


def downgrade() -> None:
    """Delete only the rows this migration seeded, by slug.

    Other property_types rows created at runtime are untouched.
    """
    seeded_slugs = tuple(row[2] for row in _PROPERTY_TYPE_SEED)
    if not seeded_slugs:
        return

    # Parameterised DELETE — only the rows we seeded, keyed by slug.
    op.execute(
        """
        DELETE FROM property_types
        WHERE slug = ANY(CAST(:slugs AS VARCHAR[]))
        """,
        {"slugs": list(seeded_slugs)},
    )
