"""Core functionality for NFM-DB API."""

from nfm_db.core.auth import (  # noqa: F401
    AuthenticationError,
    ForbiddenError,
    RequirePermission,
    RequireRole,
    UnauthorizedError,
    get_current_active_user,
    get_current_user,
    require_admin,
    require_admin_or_reviewer,
    require_assign_roles,
    require_create_post,
    require_delete_post,
    require_edit_post,
    require_editor,
    require_publish_post,
    require_review_post,
    require_reviewer,
)

__all__ = [
    "get_current_user",
    "get_current_active_user",
    "UnauthorizedError",
    "ForbiddenError",
    "AuthenticationError",
    "RequirePermission",
    "RequireRole",
    "require_admin",
    "require_editor",
    "require_reviewer",
    "require_admin_or_reviewer",
    "require_create_post",
    "require_edit_post",
    "require_delete_post",
    "require_publish_post",
    "require_review_post",
    "require_assign_roles",
]
