#!/usr/bin/env python3
"""Emit a STANDARD_PROPERTIES ontology-coverage report (NFM-3582).

Loads the canonical ontology payload and re-uses the same classifier as
``tests/test_ontology_property_coverage.py`` so the markdown report and
the CI gate never disagree.

Usage::

    cd apps/api
    python -m scripts.ontology_property_coverage_report \\
        --output ../../docs/verification/NFM-3582-coverage.md

Exit code is always 0. The pytest gate owns the pass/fail decision; this
CLI just mirrors the classifier so the report can be regenerated without
booting a test run and reviewed in code review without a DB.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make ``apps/api/src`` importable so we can use the production
# property_catalog alongside the test helper. Resolved from the repo root
# (Path(__file__).resolve().parents[3]) so the script works whether invoked
# from the repo root or apps/api.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_API_SRC = _REPO_ROOT / "apps" / "api" / "src"
if str(_API_SRC) not in sys.path:
    sys.path.insert(0, str(_API_SRC))

# pyproject.toml sets ``pythonpath = ["src", "."]`` so ``tests.*`` resolves
# from apps/api; we extend the same hint for repo-root invocations.
_TESTS_DIR = _REPO_ROOT / "apps" / "api" / "tests"
if str(_TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(_TESTS_DIR))

from nfm_db.core.property_catalog import STANDARD_PROPERTIES  # noqa: E402

from tests._helpers.ontology_property_coverage import (  # type: ignore[import-not-found]  # noqa: E402
    CoverageRow,
    CoverageStatus,
    canonical_fixture_path,
    compute_coverage_rows,
    coverage_metrics,
    load_ontology_payload,
)


def _format_status(row: CoverageRow) -> str:
    """Compact markdown cell describing a row's status + ontology presence."""
    if row.status is CoverageStatus.MAPPED:
        return "✅ mapped (property_categories ∩ entity_required_properties)"
    if row.status is CoverageStatus.PARTIAL:
        surfaces = []
        if row.in_property_categories:
            surfaces.append("property_categories")
        if row.in_entity_required_properties:
            surfaces.append("entity_required_properties")
        return f"⚠️  partial (in: {', '.join(surfaces)})"
    return "❌ missing (in: <none>)"


def _render_row_markdown(row: CoverageRow) -> str:
    """Render one coverage row in markdown table format."""
    cells = [
        f"`{row.alias}`",
        f"`{row.standard_name}`",
        _format_status(row),
        row.remediation or "—",
    ]
    return "| " + " | ".join(cells) + " |"


def _render_markdown(
    rows: list[CoverageRow],
    metrics: dict[str, object],
    fixture_path: Path,
) -> str:
    """Render the human-readable coverage report."""
    lines: list[str] = []
    lines.append("# NFM-3582: STANDARD_PROPERTIES ontology coverage")
    lines.append("")
    lines.append(
        "Generated by `apps/api/scripts/ontology_property_coverage_report.py`. "
        "The pytest gate in `tests/test_ontology_property_coverage.py` uses "
        "the same classifier and asserts every alias resolves through "
        "`property_categories[].standard_properties` ∪ "
        "`entity_types[].required_properties`."
    )
    lines.append("")
    lines.append("## Sources")
    lines.append("")
    lines.append(
        "- Alias dictionary: `apps.api.src.nfm_db.core.property_catalog.STANDARD_PROPERTIES` "
        f"({len(STANDARD_PROPERTIES)} alias(es) → "
        f"{metrics['unique_standard_names']} unique standard name(s))"
    )
    lines.append(f"- Canonical ontology fixture: `{fixture_path}`")
    lines.append(
        "- Ontology loader contract: `apps.api.src.nfm_db.services.extraction_prompt."
        "_build_ontology_standard_names_block`"
    )
    lines.append("")

    lines.append("## Headline metrics")
    lines.append("")
    lines.append(f"- Total aliases: **{metrics['total_aliases']}**")
    lines.append(
        f"- Unique standard names: **{metrics['unique_standard_names']}**"
    )
    lines.append(
        f"- Mapped (alias-level): **{metrics['by_status']['mapped']}** "
        f"({metrics['alias_pct']:.1f}%)"
    )
    lines.append(
        f"- Partial: **{metrics['by_status']['partial']}** "
        f"(name in only one ontology surface)"
    )
    lines.append(
        f"- Missing: **{metrics['by_status']['missing']}** "
        f"(name absent from the ontology)"
    )
    lines.append(
        f"- Standard-name coverage (de-duplicated): "
        f"**{metrics['covered_standard_names']} / "
        f"{metrics['unique_standard_names']}** "
        f"({metrics['standard_name_pct']:.1f}%)"
    )
    gate_passed = bool(metrics["gate_passed"])
    lines.append("")
    if gate_passed:
        lines.append("Coverage gate: **PASS** ✅")
    else:
        lines.append("Coverage gate: **FAIL** ❌")
        lines.append("")
        lines.append(
            "Follow-up issues MUST be filed for every row below with status "
            "≠ mapped; the AC for NFM-3582 is satisfied once the gate "
            "passes (i.e., every alias has status `mapped`)."
        )
    lines.append("")

    # Per-row table
    lines.append("## Per-alias coverage")
    lines.append("")
    lines.append(
        "| Alias | Standard name | Status | Remediation |"
    )
    lines.append("| --- | --- | --- | --- |")
    for row in rows:
        lines.append(_render_row_markdown(row))
    lines.append("")

    # Remediation summary tables
    missing_rows = [r for r in rows if r.status is CoverageStatus.MISSING]
    partial_rows = [r for r in rows if r.status is CoverageStatus.PARTIAL]

    if missing_rows:
        lines.append("## Missing — fill canonical ontology fixture")
        lines.append("")
        lines.append(
            "These standard names do not appear in either ontology surface. "
            "Add a new ontology entry whose `standard_properties` (under "
            "`property_categories[]`) or `required_properties` (under "
            "`entity_types[]`) equals the listed name."
        )
        lines.append("")
        lines.append("| Standard name | Aliases (legacy) | Suggested ontology node |")
        lines.append("| --- | --- | --- |")
        for std_name in sorted({r.standard_name for r in missing_rows}):
            aliases = sorted(
                {r.alias for r in missing_rows if r.standard_name == std_name}
            )
            lines.append(
                f"| `{std_name}` | {', '.join(f'`{a}`' for a in aliases)} | "
                "Add a `property_categories[]` entry whose "
                f"`standard_properties` includes `{std_name}`, OR add "
                f"`{std_name}` to an `entity_types[].required_properties[]` "
                "list. |"
            )
        lines.append("")

    if partial_rows:
        lines.append("## Partial — fill missing ontology surface")
        lines.append("")
        lines.append(
            "These standard names appear in only one ontology surface "
            "(`property_categories[]` or `entity_types[].required_properties`). "
            "Add the name to the missing surface so the alias is reachable "
            "from both the categories block and the standard names block."
        )
        lines.append("")
        lines.append("| Standard name | Aliases (legacy) | In property_categories | In required_properties | Action |")
        lines.append("| --- | --- | --- | --- | --- |")
        for std_name in sorted({r.standard_name for r in partial_rows}):
            aliases = sorted(
                {r.alias for r in partial_rows if r.standard_name == std_name}
            )
            sample = next(r for r in partial_rows if r.standard_name == std_name)
            in_cat = "✅" if sample.in_property_categories else "❌"
            in_req = "✅" if sample.in_entity_required_properties else "❌"
            if not sample.in_property_categories:
                action = f"Add `{std_name}` under `property_categories[].standard_properties`."
            else:
                action = f"Add `{std_name}` under `entity_types[].required_properties`."
            lines.append(
                f"| `{std_name}` | {', '.join(f'`{a}`' for a in aliases)} | "
                f"{in_cat} | {in_req} | {action} |"
            )
        lines.append("")

    lines.append("## Reproducing this report")
    lines.append("")
    lines.append("```bash")
    lines.append("cd apps/api")
    lines.append(
        "python -m scripts.ontology_property_coverage_report \\\n"
        "    --output ../../docs/verification/NFM-3582-coverage.md"
    )
    lines.append("")
    lines.append("# Companion pytest gate (FAIL while fixture is empty)")
    lines.append("python -m pytest tests/test_ontology_property_coverage.py -v")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Emit a STANDARD_PROPERTIES ontology-coverage report."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "docs" / "verification" / "NFM-3582-coverage.md",
        help="Markdown output path (default: docs/verification/NFM-3582-coverage.md).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Also print the rendered markdown to stdout.",
    )
    args = parser.parse_args(argv)

    fixture = canonical_fixture_path()
    if not fixture.exists():
        print(f"error: canonical ontology fixture not found at {fixture}", file=sys.stderr)
        return 2

    payload = load_ontology_payload(fixture)
    rows = compute_coverage_rows(STANDARD_PROPERTIES, payload)
    metrics = coverage_metrics(rows)

    markdown = _render_markdown(rows, metrics, fixture)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")

    summary = (
        f"wrote {args.output} | total={metrics['total_aliases']} "
        f"unique={metrics['unique_standard_names']} "
        f"mapped={metrics['by_status']['mapped']} "
        f"partial={metrics['by_status']['partial']} "
        f"missing={metrics['by_status']['missing']} "
        f"gate={'PASS' if metrics['gate_passed'] else 'FAIL'}"
    )
    print(summary)
    if args.stdout:
        print()
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
