#!/usr/bin/env python3
"""Emit a STANDARD_PROPERTIES ontology-coverage report (NFM-3531-A).

Loads the canonical ontology payload and re-uses the same loader as
``tests/test_ontology_property_coverage.py`` so the markdown report and
the CI gate never disagree.

Usage::

    cd apps/api
    python -m scripts.ontology_coverage_report \\
        --output ../../docs/verification/NFM-3531-coverage.md

Exit code 0 always. The pytest gate owns the pass/fail decision; the CLI
just mirrors the loader so the report can be regenerated without a test
run and reviewed in code review without booting a DB.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Make ``apps/api/src`` importable so we can use the production
# property_catalog alongside the test loader. Resolved from the repo root
# (``Path(__file__).resolve().parents[3]``) so the script works whether
# invoked from the repo root or apps/api.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_API_SRC = _REPO_ROOT / "apps" / "api" / "src"
if str(_API_SRC) not in sys.path:
    sys.path.insert(0, str(_API_SRC))

from nfm_db.core.property_catalog import STANDARD_PROPERTIES  # noqa: E402

# Import the neutral helper directly so the loader is byte-identical to
# the pytest gate WITHOUT dragging pytest into this CLI's runtime deps.
# pyproject.toml sets ``pythonpath = ["src", "."]`` so ``tests.*`` resolves
# from apps/api; we extend the same hint for repo-root invocations.
_TESTS_DIR = _REPO_ROOT / "apps" / "api" / "tests"
if str(_TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(_TESTS_DIR))

from tests._helpers.ontology_coverage import (  # type: ignore[import-not-found]  # noqa: E402
    canonical_fixture_path,
    collect_ontology_property_names,
    coverage_metrics,
    load_ontology_payload,
)


def _render_markdown(metrics: dict[str, object], fixture_path: Path) -> str:
    """Render the human-readable coverage report."""
    lines: list[str] = []
    lines.append("# NFM-3531-A: STANDARD_PROPERTIES ontology coverage")
    lines.append("")
    lines.append(
        "Generated by `apps/api/scripts/ontology_coverage_report.py`. "
        "The pytest gate in `tests/test_ontology_property_coverage.py` "
        "uses the same loader and asserts 100% coverage."
    )
    lines.append("")
    lines.append(f"- Fixture: `{fixture_path}`")
    lines.append(f"- STANDARD_PROPERTIES total: **{metrics['total']}**")
    lines.append(f"- Covered: **{metrics['covered_count']}**")
    lines.append(f"- Missing: **{metrics['missing_count']}**")
    lines.append(f"- Coverage: **{metrics['pct']:.1f}%**")
    lines.append("")

    missing = metrics["missing"]
    if isinstance(missing, list) and missing:
        lines.append(
            "Coverage gate: **FAIL** — NFM-3531-C must populate "
            "`property_categories[].standard_properties` (and "
            "`entity_types[].required_properties`) until every alias below "
            "is covered."
        )
        lines.append("")
        lines.append("## Missing keys")
        lines.append("")
        lines.append("Every entry below MUST appear in the canonical ontology:")
        lines.append("")
        for name in missing:
            lines.append(f"- `{name}`")
        lines.append("")
    else:
        lines.append("Coverage gate: **PASS**")
        lines.append("")
        lines.append("## All keys covered")
        lines.append("")
        lines.append(
            "Every alias in `STANDARD_PROPERTIES` resolves through the "
            "canonical ontology."
        )
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=_REPO_ROOT / "docs" / "verification" / "NFM-3531-coverage.md",
        help="Markdown output path (default: docs/verification/NFM-3531-coverage.md)",
    )
    parser.add_argument(
        "--fixture",
        type=Path,
        default=None,
        help="Override the canonical ontology JSON path",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit JSON metrics to stdout instead of rendering markdown",
    )
    args = parser.parse_args()

    if args.fixture:
        os.environ["NFM_ONTOLOGY_COVERAGE_FIXTURE"] = str(args.fixture)

    fixture_path = canonical_fixture_path()
    if not fixture_path.exists():
        print(
            f"[error] Canonical ontology fixture not found at {fixture_path}",
            file=sys.stderr,
        )
        return 1

    payload = load_ontology_payload(fixture_path)
    ontology_names = collect_ontology_property_names(payload)
    metrics = coverage_metrics(STANDARD_PROPERTIES.keys(), ontology_names)

    if args.json:
        import json

        json.dump(metrics, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
        return 0

    report = _render_markdown(metrics, fixture_path)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(
        f"Wrote {args.output} "
        f"({metrics['covered_count']}/{metrics['total']} = "
        f"{metrics['pct']:.1f}% covered, "
        f"{metrics['missing_count']} missing)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
